Using the new TreeRecursion extensions for MailExplorer
mjansenDatabay/ILIAS pull request #6
Opened 2019-06-11 08:55 UTC by legionth

2019-06-12 08:11 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailExplorer.php
> +            ->custom($path, 'something');
`something` ?

2019-06-13 08:35 UTC, mjansenDatabay requested changes
Only one tiny issue.

In General: For the final implementation, we shoul get rid of the `ilTreeExplorerGUI` inheritance.

2019-07-03 10:01 UTC, mjansenDatabay approved these changes
LGTM, thx: Please remove the "[WIP"] prefix and resolve the reaming conflict.

2019-07-04 12:08 UTC, mjansenDatabay commented
@legionth There is one remaining conflict :-).

2019-07-04 12:23 UTC, legionth commented
:roll_eyes: I'll fix it.

2019-07-04 12:28 UTC, legionth commented
Hm, I would need to rebase `feature-mail-tree-slate` for the current trunk first.
Is this ok for you or should we about another way to release this for the core?

2019-07-04 13:36 UTC, legionth commented
Rebased :tada:

2019-07-04 13:47 UTC, merged